version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.12
  pre_build:
    commands:
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      - apt-get update && apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli
      - $(aws ecr get-login --no-include-email --region ap-south-1)
  build:
    commands:
      - docker build -t goecho .
  post_build:
    commands:
      - docker tag goecho:latest 085821022607.dkr.ecr.ap-south-1.amazonaws.com/goecho:latest
      - docker push 085821022607.dkr.ecr.ap-south-1.amazonaws.com/goecho:latest
artifacts:
  files:
    - goecho
