version: 0.2

phases:
  install:
   runtime-versions:
     golang: 1.12
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - go build main.go
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - goecho
